//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:2.0.50727.3655
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace winxargs.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("winxargs.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Date に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string COLUMN_DATE {
            get {
                return ResourceManager.GetString("COLUMN_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ext に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string COLUMN_EXTENTION {
            get {
                return ResourceManager.GetString("COLUMN_EXTENTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string COLUMN_FILE {
            get {
                return ResourceManager.GetString("COLUMN_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Size に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string COLUMN_LENGTH {
            get {
                return ResourceManager.GetString("COLUMN_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Are you sure to start a process?
        ///
        ///Filename:
        ///{0}
        ///
        ///Arguments:
        ///{1} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string S_ARE_YOU_SURE_TO_LAUNCH {
            get {
                return ResourceManager.GetString("S_ARE_YOU_SURE_TO_LAUNCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;Edit...&gt; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string S_EDIT_ITEM {
            get {
                return ResourceManager.GetString("S_EDIT_ITEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to save to ini に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string S_INISAVE_FAILED {
            get {
                return ResourceManager.GetString("S_INISAVE_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Name &quot;{0}&quot; already exists. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string S_NAME_ALREADYEXISTS {
            get {
                return ResourceManager.GetString("S_NAME_ALREADYEXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Name should not be empty. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string S_NAME_ISEMPTY {
            get {
                return ResourceManager.GetString("S_NAME_ISEMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No config selected. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string S_NO_CONFIG {
            get {
                return ResourceManager.GetString("S_NO_CONFIG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No Items に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string S_NO_ITEMS {
            get {
                return ResourceManager.GetString("S_NO_ITEMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (Complete) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string S_PROCESS_COMPLETE {
            get {
                return ResourceManager.GetString("S_PROCESS_COMPLETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (Running) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string S_PROCESS_RUNNING {
            get {
                return ResourceManager.GetString("S_PROCESS_RUNNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Return value =&gt; {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string S_PROGFINISHED_WITH_RETVAL {
            get {
                return ResourceManager.GetString("S_PROGFINISHED_WITH_RETVAL", resourceCulture);
            }
        }
    }
}
